server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
spring:
  security:
    user:
      name: user
      password: password1

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
